<?php

namespace ArcaSolutions\CoreBundle\Repository;

use ArcaSolutions\CoreBundle\Entity\Domain;
use Doctrine\ORM\EntityRepository;

/**
 * DomainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainRepository extends EntityRepository
{
    /**
     * @author Diego de Biagi <diego.biagi@arcasolutions.com>
     * @since VERSION
     * @param string $term Id or url.
     * @return Domain
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneByIdOrUrl($term) {
        $qb = $this->createQueryBuilder('domain');

        return $qb->where($qb->expr()->orX('domain.url = :term', 'domain.id = :term'))
            ->setParameter(':term', $term)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
