imports:
    - { resource: config.yml }

framework:
    validation:
        cache: validator.mapping.cache.doctrine.apc

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

services:
    json_formatter:
        class: Monolog\Formatter\JsonFormatter
        calls: [['includeStacktraces']]

monolog:
    handlers:
        main:
            type: rotating_file
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            max_files: 7
            formatter: json_formatter

assetic:
    use_controller:
        enabled: '%kernel.debug%'
        profiler: false
